//go:build !ignore_autogenerated

// Code generated by hand (controller-gen not available). DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeepCopyInto copies all properties into another VNodePool.
func (in *VNodePool) DeepCopyInto(out *VNodePool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of VNodePool.
func (in *VNodePool) DeepCopy() *VNodePool {
	if in == nil {
		return nil
	}
	out := new(VNodePool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *VNodePool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties into another VNodePoolList.
func (in *VNodePoolList) DeepCopyInto(out *VNodePoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VNodePool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of VNodePoolList.
func (in *VNodePoolList) DeepCopy() *VNodePoolList {
	if in == nil {
		return nil
	}
	out := new(VNodePoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *VNodePoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties into another VNodePoolSpec.
func (in *VNodePoolSpec) DeepCopyInto(out *VNodePoolSpec) {
	*out = *in
	out.TenantRef = in.TenantRef
	out.PerNodeResources = in.PerNodeResources
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy returns a deep copy of VNodePoolSpec.
func (in *VNodePoolSpec) DeepCopy() *VNodePoolSpec {
	if in == nil {
		return nil
	}
	out := new(VNodePoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into another VNodePoolStatus.
func (in *VNodePoolStatus) DeepCopyInto(out *VNodePoolStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of VNodePoolStatus.
func (in *VNodePoolStatus) DeepCopy() *VNodePoolStatus {
	if in == nil {
		return nil
	}
	out := new(VNodePoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into another VNode.
func (in *VNode) DeepCopyInto(out *VNode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of VNode.
func (in *VNode) DeepCopy() *VNode {
	if in == nil {
		return nil
	}
	out := new(VNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *VNode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties into another VNodeList.
func (in *VNodeList) DeepCopyInto(out *VNodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of VNodeList.
func (in *VNodeList) DeepCopy() *VNodeList {
	if in == nil {
		return nil
	}
	out := new(VNodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *VNodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties into another VNodeSpec.
func (in *VNodeSpec) DeepCopyInto(out *VNodeSpec) {
	*out = *in
	out.Capacity = in.Capacity
}

// DeepCopy returns a deep copy of VNodeSpec.
func (in *VNodeSpec) DeepCopy() *VNodeSpec {
	if in == nil {
		return nil
	}
	out := new(VNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into another VNodeStatus.
func (in *VNodeStatus) DeepCopyInto(out *VNodeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of VNodeStatus.
func (in *VNodeStatus) DeepCopy() *VNodeStatus {
	if in == nil {
		return nil
	}
	out := new(VNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies TenantRef.
func (in *TenantRef) DeepCopyInto(out *TenantRef) {
	*out = *in
}

// DeepCopy returns a deep copy of TenantRef.
func (in *TenantRef) DeepCopy() *TenantRef {
	if in == nil {
		return nil
	}
	out := new(TenantRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies NodeResources.
func (in *NodeResources) DeepCopyInto(out *NodeResources) {
	*out = *in
}

// DeepCopy returns a deep copy of NodeResources.
func (in *NodeResources) DeepCopy() *NodeResources {
	if in == nil {
		return nil
	}
	out := new(NodeResources)
	in.DeepCopyInto(out)
	return out
}
